server:
  port: 8081

port: 8011
proxy:
  port: 8011
  noOfConnectionsToRealServer: 10
spring:
  profiles:
    active:
      server, proxyForTests

clients:
  proxyTestServer: http://localhost:8081/geometricServer