server:
  port: 8081

port: 5000
nettyPort: 5001
timeoutInSeconds: 180
proxy:
  port: 8011
  noOfConnectionsToRealServer: 10
spring:
  profiles:
    active:
      server, proxyForTests

clients:
  proxyTestServer: http://localhost:8081/geometricServer

logging:
  level:
    catAndDogStudio.geometricfootballserver.infrastructure.messageHandlers.netty.MessageHandlingStrategy: DEBUG
    catAndDogStudio.geometricfootballserver.infrastructure.messageHandlers.netty.MessageSender: DEBUG